name: Deploy gRPC Sentiment Server

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select environment to deploy'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - prod

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy to the server via SSH
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            set -e

            ENV='${{ github.event.inputs.environment }}'
            WORK_DIR='${{ secrets.SERVER_DEPLOYMENT_PATH }}'

            export HOME=/var/www
            mkdir -p "$HOME"

            echo ">>> Deploying gRPC Sentiment Server to $WORK_DIR ($ENV)"

            mkdir -p "$WORK_DIR"
            cd "$WORK_DIR"

            REPO_DIR="$(pwd -P)"
            git config --global --add safe.directory "$REPO_DIR"

            if [ ! -d ".git" ]; then
              git clone git@github.com:zoltanpal/grpc-sentiment-server.git .
            fi

            git fetch origin
            git checkout '${{ github.ref_name }}'
            git reset --hard "origin/${{ github.ref_name }}"
            git clean -fd

            # Fix ownership for runtime
            sudo chown -R www-data:www-data $WORK_DIR

            # Set up Python virtual environment 
            if [ ! -d ".venv" ]; 
              then python -m venv .venv 
            fi

            source .venv/bin/activate
            pip install --upgrade pip setuptools wheel
            pip install -e .

            echo ">>> Restarting gRPC sentiment service" 
            # sudo restart grpc-sentiment.service 
            # sudo systemctl status grpc-sentiment.service --no-pager
